# Generated by Django 5.1.1 on 2024-11-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción de la Alimentación')),
            ],
            options={
                'verbose_name': 'Alimentación',
                'verbose_name_plural': 'Alimentaciones',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción de la Distribución')),
            ],
            options={
                'verbose_name': 'Distribución',
                'verbose_name_plural': 'Distribuciones',
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('scientific_name', models.CharField(max_length=255, verbose_name='Nombre Científico')),
                ('average_size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Talla Promedio (cm)')),
                ('conservation_status', models.CharField(choices=[('LC', 'Menor Preocupación'), ('NT', 'Casi Amenazado'), ('VU', 'Vulnerable'), ('EN', 'En Peligro'), ('CR', 'En Peligro Crítico'), ('EW', 'Extinto en Estado Silvestre'), ('EX', 'Extinto')], max_length=50, verbose_name='Estado de Conservación')),
                ('fishing_season', models.CharField(max_length=255, verbose_name='Estación de Temporada de Pesca')),
                ('fishing_bans', models.CharField(max_length=500, verbose_name='Vedas')),
                ('water_temperature', models.CharField(max_length=100, verbose_name='Temperatura del Agua que Habita')),
                ('image', models.ImageField(upload_to='fish_images/', verbose_name='Imagen del Pez')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.diet', verbose_name='Alimentación')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.distribution', verbose_name='Distribución')),
            ],
            options={
                'verbose_name': 'Pez',
                'verbose_name_plural': 'Peces',
            },
        ),
    ]
