# Generated by Django 5.1.1 on 2024-11-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_fish_image_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='sexual_dimorphism',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default=1, max_length=50, verbose_name='Dismofirmo sexual'),
            preserve_default=False,
        ),
    ]
