# Generated by Django 5.1.1 on 2024-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_fish_sexual_dimorphism'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfish',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tamaño (cm)'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
    ]
