# Generated by Django 5.1.1 on 2024-11-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_fish_average_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='description',
            field=models.CharField(default=1, max_length=500, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
