# Generated by Django 5.1.1 on 2024-11-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_fish_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='tier',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50, verbose_name='Tiers'),
        ),
    ]
