# Generated by Django 5.1.1 on 2024-12-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_fish_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfish',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso (gramos)'),
        ),
    ]
