# Generated by Django 5.1.1 on 2024-12-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_userfish_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfish',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
