# Generated by Django 5.1.3 on 2024-12-06 03:09

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_remove_userfish_image_remove_userfish_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Main.models.Fish.get_media_path_fish, verbose_name='Imagen del Pez'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=Main.models.User.get_media_path, verbose_name='Foto del Usuario'),
        ),
        migrations.AlterField(
            model_name='userfish',
            name='biggest_fish_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Main.models.UserFish.get_media_path_userfish, verbose_name='Foto del pez más grande'),
        ),
        migrations.AlterField(
            model_name='userfish',
            name='prettiest_fish_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Main.models.UserFish.get_media_path_userfish, verbose_name='Foto del pez más bonito'),
        ),
        migrations.AlterField(
            model_name='userfish',
            name='smallest_fish_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Main.models.UserFish.get_media_path_userfish, verbose_name='Foto del pez más chico'),
        ),
    ]
