# Generated by Django 5.1.1 on 2024-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_alter_fish_image_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diet',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.AlterField(
            model_name='userfish',
            name='biggest_fish_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tamaño del pez más grande (cm)'),
        ),
        migrations.AlterField(
            model_name='userfish',
            name='prettiest_fish_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tamaño del pez más bonito (cm)'),
        ),
        migrations.AlterField(
            model_name='userfish',
            name='smallest_fish_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tamaño del pez más chico (cm)'),
        ),
    ]
