# Generated by Django 5.1.3 on 2024-12-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_delete_diet_delete_distribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfish',
            name='biggest_fish_equipment',
        ),
        migrations.RemoveField(
            model_name='userfish',
            name='prettiest_fish_equipment',
        ),
        migrations.RemoveField(
            model_name='userfish',
            name='smallest_fish_equipment',
        ),
        migrations.AddField(
            model_name='userfish',
            name='biggest_fish_reel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carrete utilizado para el pez más grande'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='biggest_fish_rod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caña utilizado para el pez más grande'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='prettiest_fish_reel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carrete utilizado para el pez más bonito'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='prettiest_fish_rod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caña utilizado para el pez más bonito'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='smallest_fish_reel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carrete utilizado para el pez más chico'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='smallest_fish_rod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caña utilizado para el pez más chico'),
        ),
    ]
