# Generated by Django 5.1.3 on 2024-12-10 03:05

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_remove_userfish_biggest_fish_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(default=1, upload_to=Main.models.User.get_media_path, verbose_name='Foto banner'),
            preserve_default=False,
        ),
    ]
