# Generated by Django 5.1.3 on 2024-12-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de fondo'),
        ),
    ]
