# Generated by Django 5.1.3 on 2024-12-17 01:19

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(upload_to=Main.models.User.get_media_path, verbose_name='background'),
        ),
    ]
