# Generated by Django 5.1.1 on 2024-11-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('photo', models.ImageField(upload_to='user_photos/', verbose_name='Foto del Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured', models.BooleanField(default=False, verbose_name='Capturado')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.fish', verbose_name='Pez')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Relación Usuario-Pez',
                'verbose_name_plural': 'Relaciones Usuario-Pez',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='fishes',
            field=models.ManyToManyField(related_name='users', through='Main.UserFish', to='Main.fish', verbose_name='Peces Capturados'),
        ),
    ]
