# Generated by Django 5.1.1 on 2024-11-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_user_userfish_user_fishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fish_images', verbose_name='Imagen del Pez'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='user_photos', verbose_name='Foto del Usuario'),
        ),
    ]
