# Generated by Django 5.1.1 on 2024-11-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_fish_sexual_dimorphism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='sexual_dimorphism',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=50, verbose_name='Dismofirmo sexual'),
        ),
    ]
