# Generated by Django 5.1.1 on 2024-11-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_userfish_size_userfish_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_fish_images/', verbose_name='Foto del pez capturado'),
        ),
    ]
