# Generated by Django 5.1.1 on 2024-11-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_userfish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='average_size',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='conservation_status',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='fishing_bans',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='fishing_season',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='sexual_dimorphism',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='water_temperature',
        ),
        migrations.AlterField(
            model_name='userfish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_fish_images', verbose_name='Foto del pez capturado'),
        ),
    ]
