# Generated by Django 5.1.1 on 2024-11-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_fish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='tier',
            field=models.CharField(choices=[('SS', 'SS'), ('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='D', max_length=2, verbose_name='Tier'),
        ),
    ]
