# Generated by Django 5.1.1 on 2024-12-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_userfish_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfish',
            name='biggest_fish_equipment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipo utilizado para el pez más grande'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='biggest_fish_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación del pez más grande'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='biggest_fish_lure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Señuelo utilizado para el pez más grande'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='biggest_fish_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_fish_images', verbose_name='Foto del pez más grande'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='biggest_fish_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tamaño del pez más grande (cm)'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='biggest_fish_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso del pez más grande (gramos)'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='prettiest_fish_equipment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipo utilizado para el pez más bonito'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='prettiest_fish_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación del pez más bonito'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='prettiest_fish_lure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Señuelo utilizado para el pez más bonito'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='prettiest_fish_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_fish_images', verbose_name='Foto del pez más bonito'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='smallest_fish_equipment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipo utilizado para el pez más chico'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='smallest_fish_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación del pez más chico'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='smallest_fish_lure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Señuelo utilizado para el pez más chico'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='smallest_fish_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_fish_images', verbose_name='Foto del pez más chico'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='smallest_fish_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tamaño del pez más chico (cm)'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='smallest_fish_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso del pez más chico (gramos)'),
        ),
        migrations.AlterField(
            model_name='userfish',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
    ]
