# Generated by Django 5.1.1 on 2024-12-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_userfish_biggest_fish_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userfish',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userfish',
            name='size',
        ),
        migrations.RemoveField(
            model_name='userfish',
            name='weight',
        ),
        migrations.AddField(
            model_name='userfish',
            name='prettiest_fish_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tamaño del pez más bonito (cm)'),
        ),
        migrations.AddField(
            model_name='userfish',
            name='prettiest_fish_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso del pez más bonito (gramos)'),
        ),
    ]
